[project]
name = "pdf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pymupdf>=1.25.5",
]

[tool.setuptools]
py-modules = ["pdf_tools"]
